"""Allowlist + proxy env + tinyproxy filter rendering."""

from __future__ import annotations

from sandbox_runner.egress import (
    DEFAULT_ALLOWLIST,
    build_allowlist,
    proxy_env,
    render_tinyproxy_filter,
)


def test_default_allowlist_covers_required_hosts() -> None:
    must_have = {
        "github.com",
        "api.github.com",
        "registry.npmjs.org",
        "pypi.org",
        "files.pythonhosted.org",
        "deb.debian.org",
        "archive.ubuntu.com",
    }
    assert must_have.issubset(set(DEFAULT_ALLOWLIST))


def test_build_allowlist_dedupes_and_merges_model_host() -> None:
    out = build_allowlist(
        extra_hosts=("github.com", "mirrors.example.com"),
        model_server_host="ollama.aidev.local",
    )
    # No duplicates.
    assert len(out) == len(set(out))
    # All caller hosts present.
    assert "ollama.aidev.local" in out
    assert "mirrors.example.com" in out
    # Defaults still present.
    assert "registry.npmjs.org" in out


def test_build_allowlist_normalises_urls() -> None:
    out = build_allowlist(extra_hosts=("https://example.com/path",))
    assert "example.com" in out
    assert "https://example.com/path" not in out


def test_proxy_env_returns_all_canonical_vars() -> None:
    env = proxy_env(proxy_url="http://proxy:8888")
    assert env["HTTP_PROXY"] == "http://proxy:8888"
    assert env["HTTPS_PROXY"] == "http://proxy:8888"
    assert env["http_proxy"] == "http://proxy:8888"
    assert env["https_proxy"] == "http://proxy:8888"
    assert "localhost" in env["NO_PROXY"]


def test_proxy_env_empty_when_no_proxy() -> None:
    assert proxy_env(proxy_url=None) == {}
    assert proxy_env(proxy_url="") == {}


def test_filter_rendering_anchors_each_entry() -> None:
    rendered = render_tinyproxy_filter(["github.com", "*.npmjs.org"])
    assert "^github\\.com$" in rendered
    assert "^[^.]+\\.npmjs\\.org$" in rendered
    # Header comment is present so the file is self-documenting.
    assert "Generated by sandbox_runner.egress.render_tinyproxy_filter" in rendered
