"""Egress allowlist for sandbox containers.

The sandbox container joins a Docker network with `internal: true`, so
**no traffic leaves it directly**. The only path to the outside is the
`aidev-egress-proxy` sidecar (tinyproxy) which is also a member of that
network plus the default bridge.

This module produces:

* `DEFAULT_ALLOWLIST` — the static set of hosts every sandbox may reach.
* `build_allowlist()`  — merges in the model-server host and any extras
  configured via `AIDEV_SANDBOX_EXTRA_EGRESS_HOSTS`.
* `proxy_env()`        — the `HTTP_PROXY`/`HTTPS_PROXY`/`NO_PROXY` env
  vars we inject into the sandbox so pip / npm / git / curl pick the
  proxy up automatically.
"""

from __future__ import annotations

from collections.abc import Sequence
from urllib.parse import urlsplit

DEFAULT_ALLOWLIST: tuple[str, ...] = (
    # GitHub (clone, push, REST API, raw content, release assets, LFS)
    "github.com",
    "api.github.com",
    "codeload.github.com",
    "objects.githubusercontent.com",
    "raw.githubusercontent.com",
    "*.github.com",
    "*.githubusercontent.com",
    # npm / pnpm / yarn registries
    "registry.npmjs.org",
    "registry.yarnpkg.com",
    "*.npmjs.org",
    # PyPI / Poetry
    "pypi.org",
    "files.pythonhosted.org",
    "*.pypi.org",
    "*.pythonhosted.org",
    # OS package mirrors (Debian-based sandbox image)
    "deb.debian.org",
    "security.debian.org",
    "archive.ubuntu.com",
    "security.ubuntu.com",
    "ports.ubuntu.com",
)


def _normalise_host(value: str) -> str:
    """Strip scheme + path so an allowlist entry is always a hostname."""

    if "://" in value:
        parts = urlsplit(value)
        return parts.hostname or parts.netloc or value
    return value.split("/", 1)[0]


def build_allowlist(
    *,
    extra_hosts: Sequence[str] = (),
    model_server_host: str | None = None,
) -> list[str]:
    """Combine the default allowlist with caller-provided hosts.

    Duplicates are removed while preserving insertion order; this keeps
    the generated tinyproxy filter deterministic (and easy to diff).
    """

    seen: set[str] = set()
    out: list[str] = []
    sources: list[str] = []
    sources.extend(DEFAULT_ALLOWLIST)
    if model_server_host:
        sources.append(model_server_host)
    sources.extend(extra_hosts)
    for raw in sources:
        host = _normalise_host(raw).lower()
        if not host or host in seen:
            continue
        seen.add(host)
        out.append(host)
    return out


def proxy_env(*, proxy_url: str | None) -> dict[str, str]:
    """Return the HTTP(S)_PROXY env vars for the sandbox container.

    If `proxy_url` is None we return an empty dict so the caller can
    decide whether to skip egress entirely.
    """

    if not proxy_url:
        return {}
    return {
        "HTTP_PROXY": proxy_url,
        "HTTPS_PROXY": proxy_url,
        "http_proxy": proxy_url,
        "https_proxy": proxy_url,
        "NO_PROXY": "localhost,127.0.0.1,::1",
        "no_proxy": "localhost,127.0.0.1,::1",
    }


def render_tinyproxy_filter(allowlist: Sequence[str]) -> str:
    """Render an anchored regex filter file for tinyproxy.

    tinyproxy treats each non-comment line as a Python-style regex
    matched against the request hostname. We anchor each entry so
    `github.com` does NOT also match `evil-github.com.attacker.test`.
    """

    lines = [
        "# Generated by sandbox_runner.egress.render_tinyproxy_filter.",
        "# Each entry is an anchored regex; tinyproxy denies anything else",
        "# when `FilterDefaultDeny Yes` is set in tinyproxy.conf.",
    ]
    for host in allowlist:
        pattern = host.replace(".", r"\.").replace("*", r"[^.]+")
        lines.append(f"^{pattern}$")
    lines.append("")
    return "\n".join(lines)


__all__ = [
    "DEFAULT_ALLOWLIST",
    "build_allowlist",
    "proxy_env",
    "render_tinyproxy_filter",
]
