"""Per-task preview routing.

Two registrars are shipped:

* ``PortPreviewRegistrar`` — IP-only acceptance mode (default). Picks a
  host port from a configured range, exposes the sandbox dev server on
  it, and advertises ``http://<public-host>:<port>``. No DNS / TLS /
  reverse proxy required, which is what the Ubuntu VPS acceptance run
  uses.
* ``PreviewRegistrar`` (alias ``TraefikPreviewRegistrar``) — domain-based
  mode, retained as a future-production path. Writes a Traefik dynamic
  file to ``infra/traefik/dynamic/tasks/`` so reviewers can hit
  ``task-<id>.preview.<DOMAIN>`` once DNS + certs are configured.

The docker executor picks one based on ``SandboxConfig.preview_mode``.
"""

from __future__ import annotations

import logging
import os
import re
import threading
from dataclasses import dataclass

logger = logging.getLogger(__name__)

_TASK_ID_RE = re.compile(r"^[A-Za-z0-9_-]+$")


@dataclass(frozen=True)
class PreviewRoute:
    """One row in the per-task Traefik file."""

    task_id: str
    domain: str
    backend_url: str  # e.g. http://aidev-sandbox-abc123:3000

    @property
    def router_name(self) -> str:
        return f"aidev-preview-{self.task_id}"

    @property
    def service_name(self) -> str:
        return f"aidev-preview-svc-{self.task_id}"


def render_dynamic_config(route: PreviewRoute) -> str:
    """Render the YAML Traefik will read for this task."""

    return (
        "# Generated by sandbox_runner.preview. Do not edit by hand —\n"
        f"# this file is owned by task {route.task_id}.\n"
        "http:\n"
        "  routers:\n"
        f"    {route.router_name}:\n"
        f"      rule: Host(`{route.domain}`)\n"
        "      entrypoints:\n"
        "        - websecure\n"
        f"      service: {route.service_name}\n"
        "      tls: true\n"
        "      middlewares:\n"
        "        - aidev-security-headers@file\n"
        "        - aidev-rate-limit@file\n"
        "        - aidev-compress@file\n"
        "  services:\n"
        f"    {route.service_name}:\n"
        "      loadBalancer:\n"
        "        servers:\n"
        f"          - url: {route.backend_url}\n"
    )


class PreviewRegistrar:
    """File-system writer for Traefik dynamic preview routes.

    The registrar is intentionally side-effect-only: it doesn't poke
    Traefik directly. Traefik's file watcher (`--providers.file.watch=
    true`) picks the changes up within a second or two.
    """

    def __init__(self, *, dynamic_dir: str) -> None:
        self._dynamic_dir = dynamic_dir

    @property
    def dynamic_dir(self) -> str:
        return self._dynamic_dir

    def _path_for(self, task_id: str) -> str:
        if not _TASK_ID_RE.match(task_id):
            raise ValueError(
                f"task_id must match [A-Za-z0-9_-]+, got {task_id!r}"
            )
        return os.path.join(self._dynamic_dir, f"task-{task_id}.yml")

    def register(self, route: PreviewRoute) -> str:
        """Write the dynamic file for `route` and return its path."""

        os.makedirs(self._dynamic_dir, exist_ok=True)
        target = self._path_for(route.task_id)
        tmp = target + ".tmp"
        with open(tmp, "w", encoding="utf-8") as fh:
            fh.write(render_dynamic_config(route))
        os.replace(tmp, target)
        logger.info(
            "preview.register task_id=%s domain=%s file=%s",
            route.task_id,
            route.domain,
            target,
        )
        return target

    def deregister(self, task_id: str) -> bool:
        """Remove the dynamic file for `task_id`.

        Returns True if a file was removed, False if it didn't exist.
        """

        target = self._path_for(task_id)
        try:
            os.remove(target)
        except FileNotFoundError:
            return False
        logger.info("preview.deregister task_id=%s file=%s", task_id, target)
        return True


# Alias kept for clarity at call sites that select an explicit mode.
TraefikPreviewRegistrar = PreviewRegistrar


@dataclass(frozen=True)
class PortAllocation:
    """One port-based preview slot returned by ``PortPreviewRegistrar``.

    Carries every value the executor needs to wire a host -> container
    port mapping and to advertise the public URL back to the dashboard.
    """

    task_id: str
    host_port: int
    internal_port: int
    public_host: str

    @property
    def public_url(self) -> str:
        return f"http://{self.public_host}:{self.host_port}"

    @property
    def port_bindings(self) -> dict[str, int]:
        """Shaped for ``docker.containers.create(ports=...)``."""

        return {f"{self.internal_port}/tcp": self.host_port}


class PortPoolExhaustedError(RuntimeError):
    """Raised when no free host port is left in the configured range."""


class PortPreviewRegistrar:
    """Allocate host ports for IP-only preview URLs.

    The registrar is in-memory and process-local — one sandbox-runner
    owns the pool. It is safe across asyncio tasks because all mutation
    sits behind a ``threading.Lock`` and the methods themselves are
    synchronous (the executor calls them from ``asyncio.to_thread``).

    Re-allocating for the same ``task_id`` returns the previously
    reserved port — idempotent on the same key so the executor can call
    ``allocate`` multiple times during one session if needed.
    """

    def __init__(
        self,
        *,
        public_host: str,
        port_range_start: int,
        port_range_end: int,
    ) -> None:
        if port_range_start <= 0 or port_range_end <= 0:
            raise ValueError("preview port range must be positive")
        if port_range_end < port_range_start:
            raise ValueError(
                "preview_port_range_end must be >= preview_port_range_start; "
                f"got {port_range_start}..{port_range_end}"
            )
        self._public_host = public_host
        self._start = port_range_start
        self._end = port_range_end
        self._allocations: dict[str, int] = {}
        self._reverse: dict[int, str] = {}
        self._lock = threading.Lock()

    @property
    def public_host(self) -> str:
        return self._public_host

    @property
    def port_range(self) -> tuple[int, int]:
        return (self._start, self._end)

    def allocate(
        self,
        *,
        task_id: str,
        internal_port: int,
    ) -> PortAllocation:
        if not _TASK_ID_RE.match(task_id):
            raise ValueError(
                f"task_id must match [A-Za-z0-9_-]+, got {task_id!r}"
            )
        with self._lock:
            existing = self._allocations.get(task_id)
            if existing is not None:
                return PortAllocation(
                    task_id=task_id,
                    host_port=existing,
                    internal_port=internal_port,
                    public_host=self._public_host,
                )
            for candidate in range(self._start, self._end + 1):
                if candidate not in self._reverse:
                    self._allocations[task_id] = candidate
                    self._reverse[candidate] = task_id
                    logger.info(
                        "preview.allocate task_id=%s port=%s host=%s",
                        task_id,
                        candidate,
                        self._public_host,
                    )
                    return PortAllocation(
                        task_id=task_id,
                        host_port=candidate,
                        internal_port=internal_port,
                        public_host=self._public_host,
                    )
        raise PortPoolExhaustedError(
            f"no free preview port in {self._start}-{self._end}"
        )

    def release(self, task_id: str) -> bool:
        """Free a previously allocated port.

        Returns True if a port was released, False if nothing was held.
        """

        with self._lock:
            port = self._allocations.pop(task_id, None)
            if port is None:
                return False
            self._reverse.pop(port, None)
        logger.info("preview.release task_id=%s port=%s", task_id, port)
        return True

    def allocation_for(self, task_id: str) -> PortAllocation | None:
        with self._lock:
            port = self._allocations.get(task_id)
        if port is None:
            return None
        return PortAllocation(
            task_id=task_id,
            host_port=port,
            internal_port=0,  # not known at this layer
            public_host=self._public_host,
        )


__all__ = [
    "PortAllocation",
    "PortPoolExhaustedError",
    "PortPreviewRegistrar",
    "PreviewRegistrar",
    "PreviewRoute",
    "TraefikPreviewRegistrar",
    "render_dynamic_config",
]
