"""Per-task preview routing through Traefik's file provider.

When a sandbox brings up the frontend dev server we register a router
in Traefik so reviewers can hit it at
`task-<id>.preview.<DOMAIN>`. Traefik watches
`infra/traefik/dynamic/tasks/` and picks new files up automatically —
no reload required.
"""

from __future__ import annotations

import logging
import os
import re
from dataclasses import dataclass

logger = logging.getLogger(__name__)

_TASK_ID_RE = re.compile(r"^[A-Za-z0-9_-]+$")


@dataclass(frozen=True)
class PreviewRoute:
    """One row in the per-task Traefik file."""

    task_id: str
    domain: str
    backend_url: str  # e.g. http://aidev-sandbox-abc123:3000

    @property
    def router_name(self) -> str:
        return f"aidev-preview-{self.task_id}"

    @property
    def service_name(self) -> str:
        return f"aidev-preview-svc-{self.task_id}"


def render_dynamic_config(route: PreviewRoute) -> str:
    """Render the YAML Traefik will read for this task."""

    return (
        "# Generated by sandbox_runner.preview. Do not edit by hand —\n"
        f"# this file is owned by task {route.task_id}.\n"
        "http:\n"
        "  routers:\n"
        f"    {route.router_name}:\n"
        f"      rule: Host(`{route.domain}`)\n"
        "      entrypoints:\n"
        "        - websecure\n"
        f"      service: {route.service_name}\n"
        "      tls: true\n"
        "      middlewares:\n"
        "        - aidev-security-headers@file\n"
        "        - aidev-rate-limit@file\n"
        "        - aidev-compress@file\n"
        "  services:\n"
        f"    {route.service_name}:\n"
        "      loadBalancer:\n"
        "        servers:\n"
        f"          - url: {route.backend_url}\n"
    )


class PreviewRegistrar:
    """File-system writer for Traefik dynamic preview routes.

    The registrar is intentionally side-effect-only: it doesn't poke
    Traefik directly. Traefik's file watcher (`--providers.file.watch=
    true`) picks the changes up within a second or two.
    """

    def __init__(self, *, dynamic_dir: str) -> None:
        self._dynamic_dir = dynamic_dir

    @property
    def dynamic_dir(self) -> str:
        return self._dynamic_dir

    def _path_for(self, task_id: str) -> str:
        if not _TASK_ID_RE.match(task_id):
            raise ValueError(
                f"task_id must match [A-Za-z0-9_-]+, got {task_id!r}"
            )
        return os.path.join(self._dynamic_dir, f"task-{task_id}.yml")

    def register(self, route: PreviewRoute) -> str:
        """Write the dynamic file for `route` and return its path."""

        os.makedirs(self._dynamic_dir, exist_ok=True)
        target = self._path_for(route.task_id)
        tmp = target + ".tmp"
        with open(tmp, "w", encoding="utf-8") as fh:
            fh.write(render_dynamic_config(route))
        os.replace(tmp, target)
        logger.info(
            "preview.register task_id=%s domain=%s file=%s",
            route.task_id,
            route.domain,
            target,
        )
        return target

    def deregister(self, task_id: str) -> bool:
        """Remove the dynamic file for `task_id`.

        Returns True if a file was removed, False if it didn't exist.
        """

        target = self._path_for(task_id)
        try:
            os.remove(target)
        except FileNotFoundError:
            return False
        logger.info("preview.deregister task_id=%s file=%s", task_id, target)
        return True


__all__ = [
    "PreviewRegistrar",
    "PreviewRoute",
    "render_dynamic_config",
]
